(() => {
  'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const clamp = (v,a=0,b=1) => Math.min(b,Math.max(a,v));
  const ease = p => 1-Math.pow(1-clamp(p),3);
  const smooth = p => { p=clamp(p); return p*p*(3-2*p); };
  const mix = (a,b,p) => a+(b-a)*p;
  const progress = (t,start,duration=.65) => ease((t-start)/duration);
  const {scenes,cues,duration,voiceover} = window.CUE_TIMELINE;
  const el = new Map();
  function node(selector){ if(!el.has(selector))el.set(selector,$(selector)); return el.get(selector); }
  function pose(selector,opacity=1,x=0,y=0,scale=1,rotation=0){ const n=node(selector); if(!n)return; n.style.opacity=clamp(opacity);n.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale}) rotate(${rotation}deg)`; }
  function reveal(selector,t,start=0,delay=.75,y=32,scale=.98){const p=progress(t,start,delay);pose(selector,p,0,(1-p)*y,mix(scale,1,p));}
  function setText(selector,text){const n=node(selector);if(n.textContent!==text)n.textContent=text;}
  function setHTML(selector,text){const n=node(selector);if(n.dataset.html!==text){n.innerHTML=text;n.dataset.html=text;}}
  function tap(selector,t,at,x=0,y=0){const p=(t-at)/.8;const visible=p>=0&&p<=1;pose(selector,visible?(1-p)*.85:0,x,y,mix(.55,1.65,smooth(p)));}
  function tapTarget(selector,target,t,at){const p=(t-at)/.8;if(p<0||p>1){pose(selector,0);return;}const frame=node('#film').getBoundingClientRect(),rect=node(target).getBoundingClientRect(),scale=frame.width/1920,n=node(selector);tap(selector,t,at,(rect.left+rect.width/2-frame.left)/scale-n.offsetLeft-36,(rect.top+rect.height/2-frame.top)/scale-n.offsetTop-36);}
  function swipeTarget(selector,target,t,at){const p=(t-at)/.8;if(p<0||p>1){pose(selector,0);return;}const frame=node('#film').getBoundingClientRect(),rect=node(target).getBoundingClientRect(),scale=frame.width/1920,n=node(selector);pose(selector,Math.sin(p*Math.PI)*.75,(rect.left+rect.width/2-frame.left)/scale-n.offsetLeft-36+mix(125,-125,smooth(p)),(rect.top+rect.height/2-frame.top)/scale-n.offsetTop-36,.8);}
  function float(selector,t,start,amplitude=9,scale=1){const p=progress(t,start,.9);pose(selector,p,0,(1-p)*35+Math.sin((t-start)*1.2)*amplitude,scale*mix(.93,1,p),Math.sin((t-start)*.75)*1.6);}
  let current=0,playing=false,rate=1,lastNow=0,raf=0,speechEnabled=false,captionsEnabled=true,lastSpoken=-1,activeScene=-1;
  let uploadedAudio=Boolean(window.CUE_TIMELINE.audio?.embedded),audioUrl=null,voice=null,toastTimer;
  let realAudioNote=$('#audio-note').textContent;
  const audio=$('#narration-audio');
  const query=new URLSearchParams(location.search);const clean=query.get('clean')==='1';
  if(clean)document.body.classList.add('clean');
  function resize(){const screen=$('#screen'); const full=clean||document.fullscreenElement===screen;const width=screen.clientWidth,height=screen.clientHeight;const scale=full?Math.min(width/1920,height/1080):width/1920;$('#film').style.transform=full?`translate(${-1920*scale/2}px,${-1080*scale/2}px) scale(${scale})`:`scale(${scale})`;}
  new ResizeObserver(resize).observe($('#screen'));document.addEventListener('fullscreenchange',resize);
  const keyRows=['q w e r t y u i o p','a s d f g h j k l','⇧ z x c v b n m ⌫'];
  $('#keyboard-keys').innerHTML=keyRows.map(row=>`<div class="keyrow">${row.split(' ').map(key=>`<span class="key ${['⇧','⌫'].includes(key)?'wide':''}">${key}</span>`).join('')}</div>`).join('')+'<div class="keyrow bottom"><span class="key wide">?123</span><span class="key wide">☺</span><span class="key space">English</span><span class="key wide">↵</span></div>';
  const keyboardCopy=document.createElement('div');keyboardCopy.className='marta-keys';keyboardCopy.innerHTML=$('#keyboard-keys').innerHTML;$('.marta-ui .cue-keyboard').append(keyboardCopy);
  keyboardCopy.style.cssText='position:absolute;left:22px;right:22px;top:84px;background:#f2f1f8;padding-top:25px';
  function renderHook(t){reveal('.hook-tiny',t,-1);reveal('#hook .heading',t,-.65,.85,18);reveal('.hook-chat',t,-.6,.8,45,.96);reveal('.hook-input',t,1.3,.8,20);float('.hook-mascot',t,1.65,4);pose('.hook-dot',progress(t,.8),0,Math.sin(t)*8);$('#hook .cursor').style.opacity=Math.sin(t*5.6)>0?1:0;}
  function renderBrand(t){reveal('.brand-word',t,0,.8,30);reveal('.brand-tag',t,.2);reveal('.brand-context',t,1.1);reveal('.brand-voice',t,2.1);reveal('.brand-foot',t,3.3);pose('.brand-disc',progress(t,0),0,0,mix(.9,1,progress(t,0,1.2)));float('.brand-mascot',t,.3,13);pose('.brand-spark',progress(t,1.3),0,Math.sin(t)*10,mix(.4,1,progress(t,1.3)),Math.sin(t)*9);}
  function renderSuggest(t){reveal('.suggest-label',t,0);reveal('#suggest .heading',t,.15,.85);reveal('.app-device',t,0,.9,60,.97);reveal('.b1',t,1.65);reveal('.b2',t,4.3);float('.suggest-float',t,4.4,4);setText('#marcel-suggest',t>1.25?'Cancel':'Suggest');$('#marcel-suggest').style.transform=`scale(${t>1.0&&t<1.28?.96:1})`;tapTarget('#suggest-tap','#marcel-suggest',t,1.0);pose('#marcel-working',progress(t,1.25,.4));pose('#marcel-working img',1,0,Math.sin(t*2)*4);}
  function renderReply(t){reveal('.reply-kicker',t,.05);reveal('.reply-card',t,.15,.85,46,.965);reveal('.reply-tiny',t,2);float('.reply-mascot',t,1,8);}
  function renderContext(t){reveal('#context .heading',t,.05);float('.context-mascot',t,.4,7);reveal('.context-caption',t,1.8);pose('.timeline-path',progress(t,1),0,0,1);node('.timeline-path').style.transform=`scaleY(${progress(t,1,2)})`;reveal('.context-old',t,.6,.85);pose('.point-old',progress(t,.6));reveal('.context-now',t,3.4,.9);pose('.point-now',progress(t,3.4));}
  function renderSources(t){reveal('.sources-title',t,0);reveal('.sources-copy',t,.4);reveal('.memory-panel',t,.15,.85,45);reveal('.source-tiny',t,2);float('.source-mascot',t,1.2,4);setText('#source-trigger-text',t>1.55?'Source message':'Show source');tapTarget('.source-tap','#source-trigger-text',t,1.3);reveal('.source-quote',t,1.6,.65,18,.985);}
  function directionHeading(t){const states=[{at:0,title:'Something<br>in <span class="accent">mind?</span>',copy:'Give the conversation a direction.'},{at:3.5,title:'A little<br><span class="accent">direction.</span>',copy:'Ask her out for coffee.'},{at:8,title:'Your tone.<br><span class="accent">Your call.</span>',copy:'Flirty. With a subtle touch.'},{at:16,title:'A little<br><span class="accent">spark.</span>',copy:'A suggestion that fits the moment.'}];let s=states[0];for(const v of states)if(t>=v.at)s=v;setHTML('#direction-title',s.title);setText('#direction-caption',s.copy);reveal('#direction-title',t,s.at,.65,20);reveal('#direction-caption',t,s.at+.12,.7,20);}
  function renderDirection(t){
    const points=[[0,0],[1.8,2.5],[3,4],[4.8,6.65],[5.2,8],[5.8,8.8],[6.8,11],[7.3,11.8],[8,13.75],[8.25,14],[9.5,16],[12.5,19.1],[13,20]];
    let mapped=20;
    for(let i=1;i<points.length;i++)if(t<=points[i][0]){const a=points[i-1],b=points[i];mapped=mix(a[1],b[1],clamp((t-a[0])/(b[0]-a[0])));break;}
    t=mapped;
    directionHeading(t);reveal('.marta-ui',t,.15,.8,30,.98);float('.direction-mascot',t,.6,7);pose('.marta-chat .bubble.out',progress(t,.5));pose('.marta-chat .bubble:not(.out)',progress(t,1.2));
    pose('.settings-body',progress(t,2.5)*(1-progress(t,14,.25)));pose('.marta-keys',1-progress(t,2.5,.35));
    const goal='ask her out for coffee',count=Math.floor(clamp((t-4)/2.65)*goal.length);setHTML('#goal-value',t<4?'<span style="color:#aaa0b5">What would you like to do?</span>':goal.slice(0,count)+(t<6.9?'<span class="cursor"></span>':''));setText('#goal-edit',t<6.8?'Add':'Edit');
    const swipe=smooth((t-8)/.8);node('#tone-track').style.transform=`translate3d(${mix(265,15,swipe)}px,0,0)`;pose('#tone-natural',mix(1,.48,swipe),0,0,mix(1.16,1,swipe));pose('#tone-flirty',mix(.48,1,swipe),0,0,mix(1,1.16,swipe));node('#tone-natural').classList.toggle('chosen',swipe<.5);node('#tone-flirty').classList.toggle('chosen',swipe>=.5);node('#dot-natural').classList.toggle('on',swipe<.5);node('#dot-flirty').classList.toggle('on',swipe>=.5);setHTML('#marta-toolbar-tone',(swipe<.5?'Natural':'Flirt')+'<span class="chev">⌃</span>');
    const intensityP=progress(t,8.8,.55),knob=mix(.5,0,smooth((t-11)/.8));pose('.intensity-control',intensityP,0,(1-intensityP)*15);node('.level-knob').style.transform=`translateX(${knob*node('.intensity-control').clientWidth-13}px)`;node('.intensity-fill').style.transform=`scaleX(${knob})`;node('#level-subtle').classList.toggle('selected',knob<.25);node('#level-flirty').classList.toggle('selected',knob>=.25);setText('#tone-hint',t<8.8?'Write as you normally would.':t<11.5?'Playful warmth. A little teasing.':'Curiosity and humour. A subtle spark.');
    const load=progress(t,14,.25)*(1-progress(t,16,.25));pose('.marta-loading',load);pose('.marta-loading img',1,0,Math.sin(t*2)*5);reveal('.marta-result',t,16,.55,28);setText('#marta-suggest',t<14?'Suggest':t<16?'Cancel':'Insert');
    if(t<3.6)tapTarget('#marta-tap','#marta-toolbar-tone',t,2.15);else if(t<7.5)tapTarget('#marta-tap','#goal-edit',t,3.7);else if(t<10)swipeTarget('#marta-tap','.tone-viewport',t,8);else if(t<13)tapTarget('#marta-tap','.level-knob',t,10.9);else if(t<18.8)tapTarget('#marta-tap','#marta-suggest',t,13.75);else tapTarget('#marta-tap','#marta-suggest',t,19.1);
  }
  function renderControl(t){reveal('.control-title',t,0);reveal('.control-panel',t,.2,.8,30);reveal('.control-small',t,2.6);float('.control-mascot',t,1.5,5);node('#word-choose').classList.toggle('current',t<1.5);node('#word-review').classList.toggle('current',t>=1.5&&t<2.6);node('#word-send').classList.toggle('current',t>=2.6);
    const message='then coffee with me on saturday? 😊';
    setHTML('#draft-text',(t<.75?'':message)+(t<.75||Math.sin(t*5)>-.1?'<span class="cursor"></span>':''));pose('.send-round',1,0,0,t>2.6?1+Math.sin(Math.min((t-2.6)*Math.PI,Math.PI))*.04:1);
  }
  function renderTeam(t){reveal('.team-title',t,.1);reveal('.team-number',t,.15,.95,60,.95);reveal('.team-unit',t,.9);reveal('.team-names',t,1.2);reveal('.team-built',t,2.2);reveal('.team-undefined',t,2.8);reveal('.team-stack',t,3.2);float('.team-ghost',t,2.5,7);}
  function renderEnd(t){reveal('.end-word',t,.05,.85,25);float('.end-mascot',t,.1,4);reveal('.end-tag',t,.5,.8,20);pose('.end-dot',progress(t,.8),0,Math.sin(t)*3);}
  const renderers={hook:renderHook,brand:renderBrand,suggest:renderSuggest,reply:renderReply,context:renderContext,sources:renderSources,direction:renderDirection,control:renderControl,team:renderTeam,end:renderEnd};
  function format(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
  function cueAt(time){return cues.findIndex(c=>time>=c.start&&time<c.end);}
  function render(time){current=clamp(time,0,duration);let sceneIndex=0;scenes.forEach((scene,index)=>{const n=node('#'+scene.id);const visible=current>=scene.start-.35&&current<(scene.end===duration?duration+.1:scene.end);n.classList.toggle('active',visible);n.setAttribute('aria-hidden',String(!visible));if(visible){const p=progress(current,scene.start-.35,.35);n.style.opacity=p;renderers[scene.id](current-scene.start);}if(current>=scene.start)sceneIndex=index;});
    const cue=cueAt(current);setText('#subtitle',cue>=0?cues[cue].text:'');node('#subtitle').classList.toggle('disabled',!captionsEnabled);setText('#current-time',format(current));setText('#current-scene',scenes[sceneIndex].label);$('#seek').value=current;$('#seek').setAttribute('aria-valuetext',`${format(current)} z ${format(duration)}`);$('#playhead').style.left=`calc(${current/duration*100}% - 1.5px)`;
    scenes.forEach((s,i)=>$('#seg-'+i).style.transform=`scaleX(${clamp((current-s.start)/(s.end-s.start))})`);
    if(activeScene!==sceneIndex){activeScene=sceneIndex;$$('.scene-link').forEach((b,i)=>{b.classList.toggle('active',i===sceneIndex);b.setAttribute('aria-current',i===sceneIndex?'step':'false');});}
    return {time:current,scene:scenes[sceneIndex].id,cue};
  }
  function updatePlay(){ $('#play-icon').setAttribute('href',playing?'#i-pause':'#i-play');$('#play').setAttribute('aria-label',playing?'Zatrzymaj':'Odtwórz'); }
  function stopSpeech(){if('speechSynthesis'in window)window.speechSynthesis.cancel();lastSpoken=-1;}
  function chooseVoice(){if(!('speechSynthesis'in window))return;const voices=speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang));voice=voices.find(v=>/Samantha|Daniel|Karen|Google US English/i.test(v.name))||voices.find(v=>v.localService)||voices[0]||null;}
  if('speechSynthesis'in window){chooseVoice();speechSynthesis.addEventListener('voiceschanged',chooseVoice);}
  function speakCurrent(){if(!speechEnabled||uploadedAudio||!playing||!('speechSynthesis'in window))return;const index=cueAt(current);if(index<0)return;if(index===lastSpoken)return;lastSpoken=index;const cue=cues[index];if(current-cue.start>1)return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(cue.text);if(voice)utterance.voice=voice;utterance.lang='en-US';utterance.rate=clamp((cue.text.split(/\s+/).length/((cue.end-cue.start)/60))/160,.92,1.18)*rate;utterance.volume=.85;speechSynthesis.speak(utterance);}
  function tick(now){if(!playing)return;const delta=Math.min((now-lastNow)/1000,.25);lastNow=now;const next=uploadedAudio&&!audio.paused&&!audio.ended?audio.currentTime:current+delta*rate;render(next);speakCurrent();if(current>=duration){pause();return;}raf=requestAnimationFrame(tick);}
  function play(){if(current>=duration-.05)render(0);playing=true;lastNow=performance.now();updatePlay();if(uploadedAudio){audio.currentTime=current;audio.playbackRate=rate;audio.play().catch(()=>{toast('Nie można odtworzyć tego pliku audio.');});}cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);speakCurrent();}
  function pause(){playing=false;cancelAnimationFrame(raf);audio.pause();stopSpeech();updatePlay();}
  function seek(time){stopSpeech();if(uploadedAudio)audio.currentTime=clamp(time,0,duration);render(time);lastNow=performance.now();speakCurrent();return current;}
  function toggle(){if(playing)pause();else play();}
  function toast(message){setText('#toast',message);$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400);}
  function previous(){const start=scenes[activeScene].start;seek(current>start+1.1?start:scenes[Math.max(0,activeScene-1)].start);}
  function next(){seek(scenes[Math.min(scenes.length-1,activeScene+1)].start);}
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#screen').requestFullscreen();}catch{toast('Pełny ekran nie jest dostępny w tej przeglądarce.');}}
  async function copy(text){try{await navigator.clipboard.writeText(text);}catch{const input=document.createElement('textarea');input.value=text;document.body.append(input);input.select();document.execCommand('copy');input.remove();}toast('Skopiowano tekst lektora.');}
  scenes.forEach((scene,index)=>{const segment=document.createElement('div');segment.className='segment';segment.style.flex=scene.end-scene.start;segment.innerHTML=`<div class="segment-fill" id="seg-${index}"></div>`;$('#timeline').insertBefore(segment,$('#seek'));const btn=document.createElement('button');btn.className='scene-link';btn.innerHTML=`<small>${format(scene.start)} — ${format(scene.end)}</small><strong>${scene.label}</strong><span>${scene.note}</span>`;btn.addEventListener('click',()=>seek(scene.start+.4));$('#scene-grid').append(btn);});
  cues.forEach((cue,index)=>{const row=document.createElement('div');row.className='script-row';const time=document.createElement('button');time.className='cue-time';time.textContent=`${format(cue.start)}–${format(cue.end)}`;time.addEventListener('click',()=>seek(cue.start));const text=document.createElement('p');text.textContent=cue.text;const button=document.createElement('button');button.className='copy-line';button.textContent='⧉';button.setAttribute('aria-label','Kopiuj fragment '+(index+1));button.addEventListener('click',()=>copy(cue.text));row.append(time,text,button);$('#script-lines').append(row);});
  $('#play').addEventListener('click',toggle);$('#screen').addEventListener('click',toggle);$('#prev').addEventListener('click',previous);$('#next').addEventListener('click',next);$('#seek').addEventListener('input',e=>seek(Number(e.target.value)));$('#rate').addEventListener('change',e=>{rate=Number(e.target.value);audio.playbackRate=rate;stopSpeech();});$('#fullscreen').addEventListener('click',fullscreen);
  $('#captions').addEventListener('click',()=>{captionsEnabled=!captionsEnabled;$('#captions').classList.toggle('on',captionsEnabled);$('#captions').setAttribute('aria-pressed',String(captionsEnabled));render(current);});
  $('#speech').addEventListener('click',()=>{if(!('speechSynthesis'in window)){toast('Ta przeglądarka nie obsługuje lektora roboczego.');return;}speechEnabled=!speechEnabled;$('#speech').classList.toggle('on',speechEnabled);$('#speech').setAttribute('aria-pressed',String(speechEnabled));stopSpeech();chooseVoice();if(speechEnabled){uploadedAudio=false;audio.pause();setText('#audio-note','Odsłuch roboczy z przeglądarki. Wyłącz go, aby wrócić do nagrań ElevenLabs.');toast('Lektor roboczy włączony.');speakCurrent();}else{uploadedAudio=Boolean(audio.getAttribute('src'));setText('#audio-note',realAudioNote);if(uploadedAudio){audio.currentTime=current;audio.playbackRate=rate;if(playing)audio.play().catch(()=>toast('Nie można wznowić nagrania.'));}}});
  $('#show-script').addEventListener('click',()=>{const open=$('#transcript').classList.toggle('open');$('#show-script').textContent=open?'Schowaj tekst':'Pokaż tekst';$('#show-script').setAttribute('aria-expanded',String(open));});$('#copy-script').addEventListener('click',()=>copy(voiceover));$('#load-audio').addEventListener('click',()=>$('#audio-file').click());
  $('#audio-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;pause();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);audio.src=audioUrl;uploadedAudio=true;speechEnabled=false;$('#speech').classList.remove('on');$('#speech').setAttribute('aria-pressed','false');audio.addEventListener('loadedmetadata',()=>{realAudioNote=`${file.name} · ${format(audio.duration)} · ścieżka od 00:00. Film ma ${format(duration)}; nieprzycięte nagranie wymaga dopasowania pauz do scen.`;setText('#audio-note',realAudioNote);seek(0);},{once:true});toast('Podłączono audio. Odtwarzanie zacznie się od początku.');});
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(document.activeElement?.tagName)||e.metaKey||e.ctrlKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();toggle();}else if(e.key==='ArrowRight'){e.preventDefault();seek(current+(e.shiftKey?5:1));}else if(e.key==='ArrowLeft'){e.preventDefault();seek(current-(e.shiftKey?5:1));}else if(e.key==='Home'){e.preventDefault();seek(0);}else if(e.key==='End'){e.preventDefault();seek(duration);}else if(e.key.toLowerCase()==='f')fullscreen();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause();});
  const ready=Promise.all([document.fonts.ready,...[...document.images].map(image=>image.decode())]);
  window.CueFilm={duration,scenes,cues,seek,play,pause,render,frame:async(time)=>{pause();await ready;seek(time);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return current;},getTime:()=>current,getState:()=>({time:current,playing,rate,scene:scenes[activeScene]?.id}),setCaptions:(show)=>{captionsEnabled=Boolean(show);$('#captions').classList.toggle('on',captionsEnabled);$('#captions').setAttribute('aria-pressed',String(captionsEnabled));render(current);},ready};
  render(Number(query.get('t'))||0);resize();ready.then(()=>{resize();render(current);if(query.get('autoplay')==='1')play();});
})();
