import { guardian } from '@/services/guardian';
import { Pressable, View } from 'react-native';
import { router } from 'expo-router';
import { Screen, Copy, Card, Row, Icon, SectionHeading, TextAction, Toggle, Risk, Empty, Action, InlineError } from '@/components/ui';
import { useProtection } from '@/features/protection/useProtection';
import { useTheme, riskColors, riskFromLabel } from '@/theme/useTheme';
export default function Protection() { const { enabled, active: monitoringActive, toggleProtection, threats, apps, native, stateLabel, busy, error, status, openAccess } = useProtection(); const { colors, isDark } = useTheme(); const active = threats.filter(t => !t.reviewed && (!native || t.risk === 'Wysokie ryzyko')); const first = active[0]; return <Screen title="Ochrona">
<Card><Row><Icon name="shield" size={25} color={first ? riskColors(riskFromLabel(first.risk), isDark).foreground : colors.text} /><View style={{ flex: 1 }}><Copy style={{ color: colors.text, fontSize: 16, fontWeight: '500' }}>{monitoringActive ? 'Ochrona włączona' : enabled ? 'Ochrona niegotowa' : 'Ochrona wyłączona'}</Copy><Copy style={{ fontSize: 11 }}>{stateLabel}</Copy></View><Toggle value={enabled} onChange={toggleProtection} disabled={busy || (native && !status?.available)} label="Monitorowanie powiadomień" /></Row></Card>
<InlineError message={error} />
{native && !status?.notificationAccess && <Card><Copy>Android wymaga zgody na odczyt powiadomień. Włącz Guardian w ustawieniach dostępu.</Copy><Action secondary label="Włącz dostęp do powiadomień" onPress={openAccess} /></Card>}
{native && !status?.notificationPermission && <Action secondary label="Zezwól na ostrzeżenia" onPress={() => { guardian.warningPermission(); }} />}
<View><SectionHeading title={`Ostrzeżenia  ${active.length}`}><TextAction label="Historia" onPress={() => router.push('/alerts')} /></SectionHeading>{first ? <Pressable accessibilityRole="button" onPress={() => router.push(`/alert/${first.id}`)}><Card><Row style={{ justifyContent: 'space-between' }}><Risk label={first.risk} /><Copy style={{ fontSize: 11 }}>{first.time}</Copy></Row><Copy title style={{ fontSize: 18, lineHeight: 27, letterSpacing: -.4 }}>{first.title}</Copy><Copy>{first.explanation ?? first.signals.slice(0, 2).join(" · ")}</Copy><Row style={{ borderTopWidth: 1, borderColor: colors.border, paddingTop: 16, justifyContent: 'space-between' }}><Row style={{ gap: 7 }}><Icon name="message" size={16} /><Copy style={{ fontSize: 11 }}>{first.source}</Copy></Row><Row style={{ gap: 5 }}><Copy style={{ color: colors.text, fontSize: 11 }}>Zobacz zalecenie</Copy><Icon name="arrow" size={17} /></Row></Row></Card></Pressable> : <Empty title={native ? "Brak nowych ostrzeżeń" : "Wszystko sprawdzone"} subtitle={monitoringActive ? "Tu pojawią się ostrzeżenia po analizie nowych powiadomień." : "Nowe ostrzeżenia pojawią się tutaj po uruchomieniu monitorowania."} />}</View>
<Pressable accessibilityRole="button" onPress={() => router.push('/check')}><Card><Row><Icon name="scan" /><Copy style={{ flex: 1, color: colors.text, fontWeight: '500' }}>Sprawdź wiadomość lub link</Copy><Icon name="chevron" size={18} /></Row></Card></Pressable>
<View><SectionHeading title="Chronione aplikacje"><TextAction label="Zarządzaj" onPress={() => router.push('/settings')} /></SectionHeading><Card style={{ paddingVertical: 4 }}>{Object.entries(apps).map(([name, on], i) => <Row key={name} style={{ paddingVertical: 15, borderTopWidth: i ? 1 : 0, borderColor: colors.border }}><View style={{ padding: 9, backgroundColor: colors.secondary, borderRadius: 10 }}><Icon name="message" size={19} color={colors.secondaryText} /></View><Copy style={{ flex: 1, color: colors.text }}>{name}</Copy><Copy style={{ fontSize: 10 }}>{on && monitoringActive ? 'Monitorowane' : 'Wstrzymano'}</Copy></Row>)}</Card></View>
<Copy style={{ fontSize: 11, textAlign: 'center' }}>{native ? "Analiza nowych powiadomień · kontekst do 5 wiadomości · AI może się pomylić" : "Podgląd UI · przykładowe zdarzenia"}</Copy>
</Screen>; }
