// Objective-C API for talking to fi.mirrormsg/fbmessagebridge Go package.
//   gobind -lang=objc fi.mirrormsg/fbmessagebridge
//
// File is generated by gobind. Do not edit.

#ifndef __Fbmessagebridge_H__
#define __Fbmessagebridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FbmessagebridgeBridge;
@protocol FbmessagebridgeEventSink;
@class FbmessagebridgeEventSink;

@protocol FbmessagebridgeEventSink <NSObject>
- (void)onEvent:(NSString* _Nullable)eventType jsonPayload:(NSString* _Nullable)jsonPayload;
@end

/**
 * Bridge wraps a single messagix client plus its lifecycle. One Bridge == one
logged-in Facebook/Messenger session. Mirrors the Google Bridge struct.
 */
@interface FbmessagebridgeBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBridge creates a Facebook Messenger bridge. Kept as the platform-defaulting
entry point so existing Facebook callers are unchanged; Instagram (and any
future Meta platform) goes through NewBridgeForPlatform.
 */
- (nullable instancetype)init:(NSString* _Nullable)sessionJSON sink:(id<FbmessagebridgeEventSink> _Nullable)sink;
/**
 * NewBridgeForPlatform creates a bridge for the named Meta platform ("facebook"
or "instagram"). Both ride the identical messagix transport; the platform only
selects the cookie set and gates the Facebook-only E2EE path.
 */
- (nullable instancetype)initForPlatform:(NSString* _Nullable)sessionJSON platform:(NSString* _Nullable)platform sink:(id<FbmessagebridgeEventSink> _Nullable)sink;
/**
 * Connect opens the realtime socket and begins the initial sync. After it
returns (and the READY event fires), incoming messages arrive as MESSAGE
events on the sink. Blocking network call — keep it off the main thread.

VERIFY: messagix Client.Connect takes a context: Connect(ctx) error.
 */
- (BOOL)connect:(NSError* _Nullable* _Nullable)error;
/**
 * Disconnect stops the realtime socket and cancels in-flight work.

VERIFY: method name. messagix may expose Disconnect() or a Stop()/Close().
 */
- (void)disconnect;
/**
 * DownloadImageForCue returns decrypted image bytes, never encryption keys or signed URLs.
 */
- (NSData* _Nullable)downloadImageForCue:(NSString* _Nullable)mediaID error:(NSError* _Nullable* _Nullable)error;
/**
 * Arie does not expose MirrorMsg's watch-image format. Keeping this method as a
small stub preserves the gomobile API while avoiding the Google Messages
bridge and its unrelated dependency graph in the Messenger-only AAR.
 */
- (NSString* _Nonnull)downloadImageForWatch:(NSString* _Nullable)mediaID maxW:(long)maxW maxH:(long)maxH maxBytes:(long)maxBytes quality:(long)quality error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportSession serializes the current cookies so the session can be restored
later via NewBridge. Persist securely on the Kotlin side. Returns JSON.

VERIFY: cookies serialization. If cookies.Cookies has a String()/MarshalJSON,
use it; otherwise marshal the underlying name->value map.
 */
- (NSString* _Nonnull)exportSession:(NSError* _Nullable* _Nullable)error;
/**
 * FetchMessages returns up to count messages from a thread as JSON. messagix
backfills older messages by thread key + a timestamp/offset cursor.

VERIFY: the fetch-messages call. Unlike libgm's clean FetchMessages, messagix
historically pulls message history via FetchMessages(ctx, threadKey, ...) OR
via a GraphQL call returning an LSTable of LSInsertMessage rows. Confirm the
exact method name + params (threadKey int64, count, before-timestamp cursor).
 */
- (NSString* _Nonnull)fetchMessages:(NSString* _Nullable)threadKey count:(int64_t)count cursorJSON:(NSString* _Nullable)cursorJSON error:(NSError* _Nullable* _Nullable)error;
/**
 * GetProfilePictureURL returns the authenticated contact photo URL. A known
empty photo is distinct from metadata that has not arrived yet (an error).
 */
- (NSString* _Nonnull)getProfilePictureURL:(NSString* _Nullable)threadKey contactID:(NSString* _Nullable)contactID error:(NSError* _Nullable* _Nullable)error;
/**
 * IsLoggedIn reports whether the session has valid cookies and is usable.

VERIFY: there may be no direct IsLoggedIn(); a common proxy is "cookies
present and not expired". If messagix lacks the method, implement a cheap
check here (e.g. cookies contain c_user) rather than calling a missing API.
 */
- (BOOL)isLoggedIn;
/**
 * ListConversations returns up to count inbox threads as a JSON array. messagix
fetches threads in sync-group pages, so this drives FetchMoreThreads until it
has enough (or runs out) and returns the accumulated thread rows.

VERIFY: FetchMoreThreads signature is

	FetchMoreThreads(ctx, syncGroup int64) (*socket.KeyStoreData, *table.LSTable, error)

The threads come back inside the returned *table.LSTable (LSUpsertThread rows).
syncGroup is the inbox folder selector — VERIFY the value for the main inbox
(commonly 1). Confirm the thread row field names against the table package.
 */
- (NSString* _Nonnull)listConversations:(long)count error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)sendMessage:(NSString* _Nullable)threadKey text:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
/**
 * SendMessageIdempotent reuses the same transport message ID on retries.
 */
- (NSString* _Nonnull)sendMessageIdempotent:(NSString* _Nullable)threadKey text:(NSString* _Nullable)text transactionID:(NSString* _Nullable)transactionID error:(NSError* _Nullable* _Nullable)error;
/**
 * SendReaction adds (or, with an empty emoji, removes) a reaction to a specific
message on an E2EE (Messenger-over-WhatsApp) thread. It is the send-side mirror
of the ReactionMessage we already parse on receive: a ConsumerApplication
wrapping a ReactionMessage whose Key identifies the target message. targetFromMe
is whether the message being reacted to was sent by us (part of the message key).
Cookie (non-E2EE) threads react via messagix's SendReactionTask (sendCookieReaction).

Built for 1:1 threads (e.g. the wife's chat). Group reactions would also need the
original sender as the key Participant; not wired yet.
 */
- (NSString* _Nonnull)sendReaction:(NSString* _Nullable)threadKey targetMsgId:(NSString* _Nullable)targetMsgId targetFromMe:(BOOL)targetFromMe emoji:(NSString* _Nullable)emoji error:(NSError* _Nullable* _Nullable)error;
/**
 * SendReply sends a text message that quotes (replies to) a specific target message
on an E2EE thread. The reply links to its target via the MessageApplication
metadata's QuotedMessage (StanzaID = the target message id); the body itself is a
normal ConsumerApplication text. Cookie threads reply via messagix's SendMessageTask
with ReplyMetaData (sendCookieText below).

Built for 1:1 threads. The quoted message's Participant (sender) is omitted, which
is fine for 1:1; group replies may need it set.
 */
- (NSString* _Nonnull)sendReply:(NSString* _Nullable)threadKey targetMsgId:(NSString* _Nullable)targetMsgId targetFromMe:(BOOL)targetFromMe text:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
/**
 * SetCookies provides Facebook/Messenger cookies (a JSON object of name->value)
harvested from a logged-in facebook.com or messenger.com browser session
(devtools -> Application -> Cookies), e.g. {"c_user":"...","xs":"...","datr":"..."}.
This is the messagix analog of the Google bridge's SetCookies; for Facebook
the must-have cookies are typically c_user (the fbid) and xs (the session).

VERIFY: how messagix ingests cookies. The cookies package usually offers
NewCookiesFromString(raw) for the "name=value; name=value" header form, or a
per-key setter. Adjust to whichever your version exposes.
 */
- (BOOL)setCookies:(NSString* _Nullable)cookiesJSON error:(NSError* _Nullable* _Nullable)error;
/**
 * SetE2EEStorePath arms the E2EE spike. Kotlin calls this (with an app-private
path like <filesDir>/fbe2ee.db) BEFORE Connect; the bridge then auto-starts
the attempt when the socket reaches Ready. Passing "" disarms it.
 */
- (void)setE2EEStorePath:(NSString* _Nullable)path;
/**
 * StartE2EE runs the one-shot registration + connect attempt. Returns "" on
success or a short error string (also emitted as an FBE2EE "FAIL"). Safe to
call directly, but normally fired automatically from the Ready handler.
 */
- (NSString* _Nonnull)startE2EE:(NSString* _Nullable)storePath;
@end

/**
 * NewBridge creates a Facebook Messenger bridge. Kept as the platform-defaulting
entry point so existing Facebook callers are unchanged; Instagram (and any
future Meta platform) goes through NewBridgeForPlatform.
 */
FOUNDATION_EXPORT FbmessagebridgeBridge* _Nullable FbmessagebridgeNewBridge(NSString* _Nullable sessionJSON, id<FbmessagebridgeEventSink> _Nullable sink, NSError* _Nullable* _Nullable error);

/**
 * NewBridgeForPlatform creates a bridge for the named Meta platform ("facebook"
or "instagram"). Both ride the identical messagix transport; the platform only
selects the cookie set and gates the Facebook-only E2EE path.
 */
FOUNDATION_EXPORT FbmessagebridgeBridge* _Nullable FbmessagebridgeNewBridgeForPlatform(NSString* _Nullable sessionJSON, NSString* _Nullable platform, id<FbmessagebridgeEventSink> _Nullable sink, NSError* _Nullable* _Nullable error);

@class FbmessagebridgeEventSink;

/**
 * EventSink is implemented on the Kotlin side — IDENTICAL interface to the
Google bridge, so the same Kotlin EventSink shape works for both. The Go
event loop calls OnEvent for every incoming message, thread update, etc.
  - eventType is a stable string tag (MESSAGE, CONVERSATION, USER_ALERT,
    LOGGED_OUT, READY, UNKNOWN) — same tags the Google bridge uses where the
    concepts line up, so the Kotlin sink can treat both networks uniformly.
  - jsonPayload is the event marshaled to JSON.
 */
@interface FbmessagebridgeEventSink : NSObject <goSeqRefInterface, FbmessagebridgeEventSink> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onEvent:(NSString* _Nullable)eventType jsonPayload:(NSString* _Nullable)jsonPayload;
@end

#endif
