// Objective-C API for talking to fi.mirrormsg/whatsappbridge Go package.
//   gobind -lang=objc fi.mirrormsg/whatsappbridge
//
// File is generated by gobind. Do not edit.

#ifndef __Whatsappbridge_H__
#define __Whatsappbridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WhatsappbridgeBridge;
@protocol WhatsappbridgeEventSink;
@class WhatsappbridgeEventSink;

@protocol WhatsappbridgeEventSink <NSObject>
- (void)onEvent:(NSString* _Nullable)eventType jsonPayload:(NSString* _Nullable)jsonPayload;
@end

/**
 * Bridge wraps a single whatsmeow client plus its store + lifecycle. One Bridge
== one paired WhatsApp linked-device session.
 */
@interface WhatsappbridgeBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBridge opens (or creates) whatsmeow's device store at storePath and builds
an unconnected client. If the store already holds a paired device, the session
is restored and no pairing is needed — call Connect. Otherwise call Connect to
begin QR pairing (QR codes arrive as "QR" events on the sink).

storePath is a file path the KOTLIN side owns (e.g. ctx.filesDir + "/wa.db"),
mirroring the existing "Kotlin owns location, Go owns content" pattern. Unlike
the cookie bridges (which take a one-shot session JSON string), whatsmeow owns
and re-keys its store continuously, so we point it at a file rather than pass a
blob.
 */
- (nullable instancetype)init:(NSString* _Nullable)storePath sink:(id<WhatsappbridgeEventSink> _Nullable)sink;
/**
 * Close disconnects and closes the underlying store DB. Call when tearing the
bridge down for good (not on a transient disconnect).
 */
- (void)close;
/**
 * it just connects. Otherwise it sets up QR pairing FIRST (required before
Connect), connects, and streams the rotating QR codes to the sink as "QR"
events; the terminal result arrives as "PAIRED" / "PAIR_TIMEOUT" / "PAIR_ERROR".
Returns quickly — whatsmeow runs its read loop in the background. Keep off the
main thread anyway (the initial socket connect blocks briefly).
 */
- (BOOL)connect:(NSError* _Nullable* _Nullable)error;
/**
 * ConsolidateLidChats merges any pre-existing @lid 1:1 chat into its phone-JID
canonical, repairing conversations that split before canonicalChatJID existed.
Safe + cheap to call repeatedly (idempotent): once merged there's nothing left
to do. Self-healing — a LID whose phone mapping only becomes known later gets
folded in on a subsequent call.
 */
- (void)consolidateLidChats;
/**
 * Disconnect stops the read loop and cancels in-flight pairing. The store file is
left intact so the session restores on the next NewBridge + Connect.
 */
- (void)disconnect;
- (NSData* _Nullable)downloadImageForCue:(NSString* _Nullable)mediaID error:(NSError* _Nullable* _Nullable)error;
/**
 * Omni currently exposes text context only. Keep this API stub so the mobile
binding stays compatible without pulling the unrelated watch-image bridge and
its much larger dependency graph into the WhatsApp AAR.
 */
- (NSString* _Nonnull)downloadImageForWatch:(NSString* _Nullable)msgID maxW:(long)maxW maxH:(long)maxH maxBytes:(long)maxBytes quality:(long)quality error:(NSError* _Nullable* _Nullable)error;
/**
 * DumpContacts is a READ-ONLY diagnostic. It reports what whatsmeow's contact
store (synced from the phone's address book) holds for the chats we know about,
so we can see whether saved contact names are available and how @lid chats
behave — BEFORE wiring contact-name resolution. Emits "DIAG" events (the Kotlin
sink logs those to the exportable log). Runs at most once per session, off the
caller's thread. Changes nothing. TEMPORARY — remove once names are wired.
 */
- (void)dumpContacts;
/**
 * EnsureGroupNames fetches + caches the subject of every known group chat that we
don't already have a name for. Runs off-thread; emits CHATS_UPDATED if it
learned any new names so the watch list refreshes. Safe to call on each connect.
 */
- (void)ensureGroupNames;
/**
 * FetchMessages returns a chat's stored history as the watch's Google-schema
message JSON ({"messages":[...]}), oldest-first, capped at count (0 = all).
This is what fills the thread view — openThread on the phone merges + streams it.
 */
- (NSString* _Nonnull)fetchMessages:(NSString* _Nullable)convoID count:(long)count error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getProfilePictureURL:(NSString* _Nullable)conversationID error:(NSError* _Nullable* _Nullable)error;
/**
 * IsLoggedIn reports whether the client is connected AND authenticated right now.
 */
- (BOOL)isLoggedIn;
/**
 * IsPaired reports whether a device session exists in the store (i.e. pairing has
completed at least once), regardless of whether we're currently connected.
This is the milestone-zero persistence check: pair once, restart, expect true.
 */
- (BOOL)isPaired;
/**
 * ListConversations returns the chat list as the watch's Google-schema JSON,
most-recent first, capped at count (0 = all).
 */
- (NSString* _Nonnull)listConversations:(long)count error:(NSError* _Nullable* _Nullable)error;
/**
 * RequestPairCode generates an 8-character linking code for the given phone
number (full international format, digits only — non-digits are stripped, and
numbers starting with 0 or shorter than 7 digits are rejected). The user types
this code into WhatsApp on their primary phone (Linked devices -> Link a device
-> "Link with phone number instead"). The client MUST already be connecting
with the pairing flow live before calling this — callers connect first and wait
for the first QR event (readiness) before requesting the code. QR codes keep
generating in parallel; they can be ignored in code-pairing mode.
 */
- (NSString* _Nonnull)requestPairCode:(NSString* _Nullable)phone error:(NSError* _Nullable* _Nullable)error;
/**
 * SelfNumber returns the logged-in account's phone number — the user part of the
device JID (e.g. "15551234567"), no leading "+". Returns "" if no session is
paired yet. Read straight from the in-memory store (no I/O), so it's safe to
call cheaply; the Kotlin side uses it for the account subtitle.
 */
- (NSString* _Nonnull)selfNumber;
/**
 * SendMessage sends a plain-text message to the thread identified by convoID,
which is the chat JID string — the same value FetchMessages/ListConversations
are keyed by, so sending back to it lands in the same conversation it was read
from. whatsmeow echoes our own sent message back as an events.Message with
IsFromMe set, so it reaches the watch through the normal live path; we do NOT
optimistically insert it here. Returns {"messageId":"..."} on success; a hard
failure returns an error (gomobile surfaces it as a thrown exception to Kotlin).

NOTE on @lid chats: convoID may be a LID JID (e.g. "...@lid"). We send to it
as-is because that's the address the conversation lives under. If a particular
LID chat rejects the send on this whatsmeow version, resolve it to the phone
JID first via b.client.Store.LIDs.GetPNForLID before sending.
 */
- (NSString* _Nonnull)sendMessage:(NSString* _Nullable)convoID text:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
/**
 * SendMessageIdempotent uses a stable transport ID for a caller-provided local
transaction. whatsmeow only returns after the WhatsApp server acknowledges the
stanza, so a non-empty response ID is the confirmation boundary.
 */
- (NSString* _Nonnull)sendMessageIdempotent:(NSString* _Nullable)convoID text:(NSString* _Nullable)text transactionID:(NSString* _Nullable)transactionID error:(NSError* _Nullable* _Nullable)error;
/**
 * SendReaction adds the emoji reaction to targetMsgID (whatsmeow's BuildReaction
builds the reaction message; an empty emoji would remove it). targetFromMe tells
us whether the reacted message is ours, used to resolve the reaction key's sender
when the message isn't in our stored window.
 */
- (NSString* _Nonnull)sendReaction:(NSString* _Nullable)convoID targetMsgID:(NSString* _Nullable)targetMsgID emoji:(NSString* _Nullable)emoji targetFromMe:(BOOL)targetFromMe error:(NSError* _Nullable* _Nullable)error;
/**
 * SendReply sends text as a native WhatsApp reply quoting targetMsgID. It builds an
ExtendedTextMessage whose ContextInfo links the quoted message (StanzaID +
participant + a copy of its text for the recipient to render). Like SendMessage,
whatsmeow won't loop our own send back, so the adapter optimistically inserts it.
 */
- (NSString* _Nonnull)sendReply:(NSString* _Nullable)convoID targetMsgID:(NSString* _Nullable)targetMsgID text:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewBridge opens (or creates) whatsmeow's device store at storePath and builds
an unconnected client. If the store already holds a paired device, the session
is restored and no pairing is needed — call Connect. Otherwise call Connect to
begin QR pairing (QR codes arrive as "QR" events on the sink).

storePath is a file path the KOTLIN side owns (e.g. ctx.filesDir + "/wa.db"),
mirroring the existing "Kotlin owns location, Go owns content" pattern. Unlike
the cookie bridges (which take a one-shot session JSON string), whatsmeow owns
and re-keys its store continuously, so we point it at a file rather than pass a
blob.
 */
FOUNDATION_EXPORT WhatsappbridgeBridge* _Nullable WhatsappbridgeNewBridge(NSString* _Nullable storePath, id<WhatsappbridgeEventSink> _Nullable sink, NSError* _Nullable* _Nullable error);

@class WhatsappbridgeEventSink;

/**
 * EventSink is implemented on the Kotlin side; the Go event loop calls OnEvent
for every relevant event. Identical contract to the other two bridges, so the
Kotlin adapter pattern is unchanged.
  - eventType is a stable string tag (CONNECTED, LOGGED_OUT, QR, PAIRED,
    PAIR_TIMEOUT, PAIR_ERROR, EVENT). Receive/media tags (MESSAGE, ...) arrive
    in a later milestone.
  - jsonPayload is the event marshaled to JSON.
 */
@interface WhatsappbridgeEventSink : NSObject <goSeqRefInterface, WhatsappbridgeEventSink> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onEvent:(NSString* _Nullable)eventType jsonPayload:(NSString* _Nullable)jsonPayload;
@end

#endif
