import { StyleSheet, Text, View, type ViewProps, type TextProps, type ColorValue } from 'react-native';
import { SymbolView, type SymbolViewProps } from 'expo-symbols';
import { useTheme } from '@/theme/useTheme';

const icons = {
  trash: { ios: 'trash', android: 'delete_outline', web: 'delete_outline' },
  keyboard: { ios: 'keyboard', android: 'keyboard', web: 'keyboard' }, code: { ios: 'chevron.left.forwardslash.chevron.right', android: 'code', web: 'code' },
  search: { ios: 'magnifyingglass', android: 'search', web: 'search' }, refresh: { ios: 'arrow.clockwise', android: 'sync', web: 'sync' }, accounts: { ios: 'person.crop.circle.badge.plus', android: 'group_add', web: 'group_add' }, copy: { ios: 'doc.on.doc', android: 'content_copy', web: 'content_copy' },
  style: { ios: 'text.bubble', android: 'edit_note', web: 'edit_note' },
  back: { ios: 'arrow.left', android: 'arrow_back', web: 'arrow_back' }, shield: { ios: 'shield', android: 'shield', web: 'shield' }, scan: { ios: 'viewfinder', android: 'document_scanner', web: 'document_scanner' }, history: { ios: 'clock.arrow.circlepath', android: 'history', web: 'history' }, settings: { ios: 'gearshape', android: 'settings', web: 'settings' }, arrow: { ios: 'arrow.right', android: 'arrow_forward', web: 'arrow_forward' }, external: { ios: 'arrow.up.right', android: 'north_east', web: 'north_east' }, chevron: { ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }, message: { ios: 'message', android: 'chat_bubble', web: 'chat_bubble' }, lock: { ios: 'lock', android: 'lock', web: 'lock' }, moon: { ios: 'moon', android: 'dark_mode', web: 'dark_mode' }, sun: { ios: 'sun.max', android: 'light_mode', web: 'light_mode' }, bell: { ios: 'bell', android: 'notifications', web: 'notifications' }, warning: { ios: 'exclamationmark.triangle', android: 'warning', web: 'warning' }, check: { ios: 'checkmark', android: 'check', web: 'check' }, phone: { ios: 'phone', android: 'call', web: 'call' }, close: { ios: 'xmark', android: 'close', web: 'close' }, help: { ios: 'questionmark.circle', android: 'help', web: 'help' }, globe: { ios: 'globe', android: 'language', web: 'language' },
} satisfies Record<string, SymbolViewProps['name']>;
export type IconName = keyof typeof icons;
export function Icon({ name, size = 21, color }: { name: IconName; size?: number; color?: ColorValue }) { const { colors } = useTheme(); return <SymbolView name={icons[name]} size={size} tintColor={color ?? colors.text} />; }
export function Row({ children, ...rest }: ViewProps) { return <View {...rest} style={[styles.row, rest.style]}>{children}</View>; }
export function Copy({ children, title = false, ...rest }: TextProps & { title?: boolean }) { const { colors } = useTheme(); return <Text {...rest} style={[title ? styles.title : styles.body, { color: title ? colors.text : colors.secondaryText, fontFamily: title ? 'Manrope' : 'DMSans' }, rest.style]}>{children}</Text>; }
export function Card({ children, ...rest }: ViewProps) { const { colors } = useTheme(); return <View {...rest} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, rest.style]}>{children}</View>; }
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, title: { fontSize: 32, lineHeight: 42, fontWeight: '600', letterSpacing: -.8 }, body: { fontSize: 20, lineHeight: 30 }, card: { padding: 24, gap: 16, borderWidth: 1, borderRadius: 24, borderCurve: 'continuous' } });
