
// Objective-C API for talking to the following Go packages
//
//	fi.mirrormsg/fbmessagebridge
//	fi.mirrormsg/whatsappbridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Messagebridges_FRAMEWORK_H__
#define __Messagebridges_FRAMEWORK_H__

#include "Fbmessagebridge.objc.h"
#include "Whatsappbridge.objc.h"
#include "Universe.objc.h"

#endif
